### PR TITLE
Add environment configuration for worker relay

### PR DESCRIPTION
**Pull request by myavchik**

### CODE REVIEW

**Comment by wolfy-j** [comment]
Thank you!

**Comment by wolfy-j** [comment]
I've added the fallback to when no ENV is defined. I think ideally I would like to configure it automatically via RR.

**Comment by myavchik** [comment]
Sure, auto configuration via RR is better than duplicating code in .env and .rr.yaml.

**Comment by wolfy-j** [comment]
Can you please create a ticket in RR, we can add it to the next version.

**Comment by myavchik** [comment]
I just checked RR code and found what it already setting env RR_RELAY. Sorry, my lapse. I will create new PR with RR_WORKER renamed to RR_RELAY.

**Comment by wolfy-j** [comment]
Oh right, I've forget about it. I'm preparing the release now, I'll change it by myself.

**Pull request merged**
