### PR TITLE
Add Symfony 6 support

### PR DESCRIPTION
**Pull request by wakebit**
| Q             | A
| ------------- | ---
| Bugfix?       | ❌
| Breaks BC?    | ❌
| New feature?  | ✔️
| Issues        | 
| Docs PR       | 

This pull request adds support for Symfony 6 components.

Also, I have updated `Translator::trans(...)` method with adding a return type for compatibility with `symfony/translation-contracts:^3.0.0`'s `TranslatorInterface` (https://github.com/symfony/translation-contracts/commit/529f21f126e6c696e1129435357180c1db882dc0#diff-3daf67a6c84ebcbad65c9c7f16852754ba584904519c443a5ab1bbe756242d00R66)

### CODE REVIEW

**Comment by butschster** [comment]
Hi @wakebit!

Thank you for contribution! 
Could you please also fix [`spiral/console`](https://github.com/spiral/framework/blob/2.9/src/Console/composer.json), [`spiral/sendit`](https://github.com/spiral/framework/blob/2.9/src/SendIt/composer.json#L26), [`spiral/tokenizer`](https://github.com/spiral/framework/blob/2.9/src/Tokenizer/composer.json#L21), [`spiral/translator`](https://github.com/spiral/framework/blob/2.9/src/Translator/composer.json#L22) components?

**Comment by wakebit** [comment]
@butschster, Hi! Done.

**Comment by butschster** [comment]
Thank you! I will merge it before v2.9.2 release - 24.02.22

**Comment by roxblnfk** [comment]
I think we should update also the `symplify/monorepo-builder` package

**Comment by wakebit** [comment]
> I think we should update also the `symplify/monorepo-builder` package

@roxblnfk, see #589.

**Pull request merged**
