### PR TITLE
[validation] enable ArrayChecker

### PR DESCRIPTION
**Pull request by gam6itko**
| Q             | A
| ------------- | ---
| Bugfix?       | ✔️
| Breaks BC?    | ❌ 
| New feature?  | ❌ 
| Issues        | #... 
| Docs PR       | spiral/docs#208 

`arrayOf` validation rule not works

### CODE REVIEW

**Comment by butschster** [comment]
@gam6itko hi! Could you provide unit test for this PR?

**Comment by gam6itko** [comment]
@butschster Ok I'll do it

**Comment by gam6itko** [comment]
@butschster Done. Does it it look good?

**Comment by butschster** [comment]
> @butschster Done. Does it look good?

I think, there is a problem with namespace. Should be something like this `Spiral\Tests\Framework\Security`

**Comment by gam6itko** [comment]
@gam6itko Oops. Fixed

**Comment by gam6itko** [comment]
@butschster Can you also review [this](https://github.com/spiral/docs/pull/208) please ?

**Pull request merged**
