### PR TITLE
Issue #456: Align arguments resolving in NamedArgumentsInstantiator with native PHP 8 behavior.

### PR DESCRIPTION
**Pull request by donquixote**
| Q             | A
| ------------- | ---
| Bugfix?       | ✔️ or TBD, see changes in tests.
| Breaks BC?    | ❌ or TBD, see changes in tests.
| New feature?  | ❌ or TBD, see changes in tests.
| Issues        | #456 
| Docs PR       | (none)

The arguments resolving in `NamedArgumentsInstantiator` has some edge cases where it diverges from native behavior in PHP 8. This PR adds more test cases and attempts to align the behavior more with PHP 8.

(I might still do some tweaking with force-push)

### CODE REVIEW

**Comment by SerafimArts** [comment]
Master branch is the `2.9.x-dev` version. Are you sure these fixes should be reserved for the next minor release instead of `2.8.x` patch?

**Comment by donquixote** [comment]
I am splitting the big function, but I am not sure if that's really so helpful.
It is nice if local variables have a limited scope. But does the split really create meaningful separation?

**Comment by donquixote** [comment]
@SerafimArts I recommend to keep the commit history of this PR.
Each commit is meant to have passing tests, so we see the effect of before/after.
Only the last commit (splitting the big method) we could squash with the previous one, but we should first fine-tune.

**Comment by donquixote** [comment]
> Master branch is the 2.9.x-dev version. Are you sure these fixes should be reserved for the next minor release instead of 2.8.x patch?

Ah. Sure, I can use 2.8.x as a base instead.

**Comment by donquixote** [comment]
Base changed.

**Comment by donquixote** [comment]
I forgot to add a test for the variadic parameter. Going to do it now.

**Comment by SerafimArts** [comment]
@donquixote It's okay, dont worry. I haven't started (as you might have noticed) the review yet.

The current code for the `appendNamedArgs` function looks pretty impressive and complex, so to understand whether it can be simplified, I need to investigate its work. But since I have other tasks in my work now, I may be able to do a review either by the end or next week.

**Comment by donquixote** [comment]
Improved test coverage and support for various edge cases.

**Review by butschster — APPROVED** [review]

**Review by roxblnfk — APPROVED** [review]

**Pull request merged**
